### PR TITLE
Skip nginx provisioning if it's already provisioned.

### PR DESCRIPTION
**Pull request by msaggiorato**
This makes sure that any custom config that may exist on nginx is kept.

### CODE REVIEW

**Comment by Mte90** [comment]
I don't think that we want this, with the copy again of nginx file we are sure that the settings are always resetted because for other provisioner or changes.
Maybe we can do a check of the hash of the file, if it is the same we avoid to copy it and so on.

**Comment by msaggiorato** [comment]
Hmm, makes sense. Maybe having the ability to have custom mods to nginx file somewhere else? That way we can always replace, and reapply this custom mods that may be needed from the site.

**Comment by Mte90** [comment]
Maybe we can add a rule in the nginx file to look for another file inside the website folder, if exists will load it and we avoid bash code.

**Comment by msaggiorato** [comment]
Makes sense, I'll look into this and refactor the PR

**Comment by tomjn** [comment]
With the change in this PR, the message about nginx already being provisioned will happen on every subsequent provision. I think it might be better to either eliminate that file entirely, or provide an `nginx-custom.conf` that can be used instead if it's present.

Eitherway forking the custom site template is still the recommended and superior solution

**Comment by tomjn** [comment]
I'm going to close this out as we expect the provisioner to run everytime and i don't think this is the solution to the problem at hand

**Pull request closed without merging**
