### PR TITLE
Support cloning a git repo to wp_content

### PR DESCRIPTION
**Pull request by tomjn**
In future a branch parameter might be nice, needs testing

### CODE REVIEW

**Comment by Mte90** [comment]
It is missing an update to the readme?

**Comment by tomjn** [comment]
Yeah, it needs testing too, I only made the changes to the file

**Comment by Mte90** [comment]
Can you write something so I can do some tests?

**Comment by tomjn** [comment]
I've thought a bit more about this and I'm wondering if a `git_repos` section would be better, cloning each repo to a folder first to last

**Comment by Mte90** [comment]
A git repo to test it? In this way we can see if it is better a parameter.

**Comment by tomjn** [comment]
Closing this in favour of https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2188

**Pull request closed without merging**
