### PR TITLE
WP CLI plugin/theme is installed check refactor

### PR DESCRIPTION
**Pull request by tomjn**
Don't perform an is installed check on themes and plugins if a URL is passed

### CODE REVIEW

**Comment by Mte90** [comment]
WP-cli docs says that is possible to use a local zip, zip url or plugin slug https://developer.wordpress.org/cli/commands/plugin/install/

<blockquote><div>WordPress Developer Resources</div><div><strong><a href="https://developer.wordpress.org/">wp plugin install | WP-CLI Command | WordPress Developer Resources</a></strong></div><div>OPTIONS <plugin|zip|url>... One or more plugins to install. Accepts a plugin slug, the path to a local zip file, or a URL to a remote…</div></blockquote>

**Comment by tomjn** [comment]
@Mte90 if it's a URL to a local file or a web address, then the `is-installed` check is skipped and it's installed regardless

**Review by Mte90 — DISMISSED** [review]
Tested with:

* https://it.wordpress.org/plugins/query-monitor/
* query-monitor
* https://github.com/johnbillion/query-monitor.git
* https://github.com/johnbillion/query-monitor/archive/develop.zip

I removed the plugin folder and it was installed

**Comment by tomjn** [comment]
@Mte90 the logic was back to front, fixed now

**Comment by Mte90** [comment]
I will see if I test again today :-)

**Comment by Mte90** [comment]
* https://it.wordpress.org/plugins/query-monitor/
```
    default: Warning: Il pacchetto non può essere installato. "PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature"
    default: Warning: The 'https://it.wordpress.org/plugins/query-monitor/' plugin could not be found.
```
And there is a crash of the provisioner and VVV.

Instead https://github.com/johnbillion/query-monitor/archive/develop.zip worked

<blockquote><div>WordPress.org Italia</div><div><strong><a href="https://it.wordpress.org/plugins/query-monitor/">Query Monitor</a></strong></div><div>Query Monitor è il pannello di strumenti per sviluppatori WordPress.</div></blockquote>
<blockquote></blockquote>

**Comment by tomjn** [comment]
@Mte90 not sure that's related to this particular issue, that looks like something else. It could be a problem with  wordpress.org or network issues

**Comment by Mte90** [comment]
I agree also because from log it is a bug from wpcli.

Maybe we should add a test for an url without a zip file to avoid a crash of VVV?

**Comment by tomjn** [comment]
> Maybe we should add a test for an url without a zip file to avoid a crash of VVV?

In this scenario I would expect VVV to abort provisioning with a message about an invalid option, so there's no difference, let WP CLI give a more descriptive output.

We would also have to download said URL to see if it's a zip file too, doubling all WP CLI plugin network requests

**Comment by Mte90** [comment]
Ok so we need to handle the case of an url that is not include a ".zip" in the url with an alert so the provision not crash.

**Comment by tomjn** [comment]
No because URLs that don't end in `.zip` can still trigger the download of zip files, or redirect to zip files. This is WP CLI's responsibility, not VVV's, and there is no way that  we can do it without making a network request

This is one of those situations where trying to be helpful is unhelpful, if it's a valid URL then there is no way to know what's at the other end unless we make the request and check the result, and I'm against making additional requests. WP CLI already does this, we should not duplicate it.

**Review by Mte90 — APPROVED** [review]

**Comment by Mte90** [comment]
Ok so we can move on and merge this

**Pull request merged**
